experim_label: classif_experiment

langs:
  - en
  - es

src_langs:
  - - - en
  - - - es

model_list:
  en:
    - bert-base-uncased
    - roberta-base
    - distilbert-base-uncased
  es:
    - dccuchile/bert-base-spanish-wwm-cased
  both:
    - bert-base-uncased

hf_core_hparams:
  learning_rate: 0.00002
  num_train_epochs: 3
  warmup: 0.1
  weight_decay: 0.01
  batch_size: 16
  fc_up_layers: 0
  fc_down_layers: 2
  # model_list:
  #   en:
  #     - bert-base-uncased
  #     - roberta-base
  #     - distilbert-base-uncased
  #   es:
  #     - dccuchile/bert-base-spanish-wwm-cased
  #   both:
